name: BSE-Alert-Bot
on:
  schedule:
    - cron: '*/10 * * * *' # This tells it to run every hour
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Tools
        run: pip install requests pandas
      - name: Check BSE
        run: python scraper.py
